### ISSUE TITLE
블로그 디테일 페이지 SNS 공유하기 버튼

### ISSUE THREAD

**Issue by milooy** [9XD/9XD.github.io#22]
http://9xd.github.io/interview/2016/08/16/jason-park

하단에 SNS 공유하기 버튼 있어야 할듯
없어서 불편

**Comment by kyunooh** [comment]
@milooy 뚜우시 디스쿠스에 share 버튼이 있긴 한데 접근성이 떨어지는 모양이군요..

**Comment by kyunooh** [comment]
공유하기 말고 그냥 좋아요 버튼을 넣어서 처리하겠습니다!

**Comment by kyunooh** [comment]
https://developers.facebook.com/docs/plugins/like-button 요거요거

**Comment by kyunooh** [comment]
좋아요 버튼 완료하였습니다.
