### ISSUE TITLE
폰트가 안이쁘다

### ISSUE THREAD

**Issue by kyunooh** [9XD/9XD.github.io#3]
이쁜 한글 + 영어 폰트로 바꾸자

**Comment by kyunooh** [comment]
일단 영문폰트는 변경했다. 한글이 남았다. 나눔고딕을 써야하나...

**Comment by BongJaeChoi** [comment]
@kyunooh NotoSans로 바꿔보세여

**Comment by kyunooh** [comment]
영어는 폰트를 변경했는데 한글은 속도때문에 고민중이에요 ㅠㅠ

**Comment by kyunooh** [comment]
아 한국어도 있군요 ㅎㅎ 감사합니다

**Comment by BongJaeChoi** [comment]
NotoSans는 서브셋을 지원해요. font파일 하나당 500kb가 안되니 부담 없으실꺼구 , light~ bold까지 다양하게있어요.
서브 타이틀이나 제목에는 나눔고딕보다는 나눔스퀘어가 훨씬나아요.
[NanumSquare-master.zip](https://github.com/9XD/9XD.github.io/files/375041/NanumSquare-master.zip)

[NotoSans-subset-master.zip](https://github.com/9XD/9XD.github.io/files/375039/NotoSans-subset-master.zip)

**Comment by kyunooh** [comment]
한글에도 적용 완료!
